name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Custom tests 🧪
        uses: cypress-io/github-action@v1
        with:
          command: yarn run test
